#!/bin/bash

set -e
cd $(dirname $0)
source remote-execution.sh
password=$1

if [ "$1" = "-h" -o ! -n "$password" ]; then
    echo "Usage: $0 <new-root-password>"
    echo
    echo "Given an Edison with no root password at the specified IP address,"
    echo "configures it with a new root password and an ssh key allowing ssh"
    echo "login to the root account."
    exit 1
fi

# Sets up ssh access to the Edison based on a key pair at $HOME/.ssh/edison
# (and creates this key pair for the user if it doesn't exist yet).
# Assumes that root has no password yet.
function init_ssh_access() {
    if [ ! -f $key_file ]; then
        ssh-keygen -t dsa -f $key_file -P ''
    fi
    pubkey=$(cat $key_file.pub)
    do_on_edison <<< "
        mkdir -p .ssh
        echo '$pubkey' >> .ssh/authorized_keys &&
            echo 'Added ssh access to $target successfully.'
    "
}

# Sets the root password on the Edison.
function set_root_password() {
    password=$1
    do_on_edison <<< "
        echo 'root:$password' | chpasswd && echo 'Password set successfully.'
    "
}

echo
echo 'Setting up root account.'
connect_ethernet
init_ssh_access
set_root_password $password
