#!/bin/bash
# Copyright 2015 The Project Buendia Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

set -e
TOOLS=../../tools
$TOOLS/fetch http://downloadmirror.intel.com/24389/eng/edison-image-rel1-maint-rel1-ww42-14.zip 9a7509341cbf936c662af3e46f1b0f34 /tmp/edison-firmware.zip
