#!/bin/bash
# Copyright 2015 The Project Buendia Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

set -e
cd $(dirname $0)
source remote-execution.sh
date="$*"

if [ "$1" = "-h" ]; then
    echo "Usage: $0 [YYYY-MM-DD HH:MM:SS]"
    echo
    echo "Sets the clock on the Edison server to match this host's clock,"
    echo "or to a specified date and time."
    exit 1
fi

if [ -z "$date" ]; then
    date=$(date '+%Y-%m-%d %H:%M:%S')
fi

do_on_edison <<< "
    echo 'Setting system clock to $date.'
    date -s '$date'
    touch -t '$date' /var/lib/systemd/clock
"
