#!/bin/bash

set -e
cd $(dirname $0)
source remote-execution.sh
password=$1
setup_ssid_psk=$2
repo_url=$3

# Default to using our jenkins server as the repo for our released packages.
repo_url=${repo_url-http://104.155.14.26:9001}

if [ "$1" == "-h" -o ! -n "$setup_ssid_psk" ]; then
  echo "Usage: $0 <new-root-password> <setup-ssid>[:<psk-password>] [<repo-url>]"
  echo
  echo "Completely erases an Edison and brings it to a basic state enabling"
  echo "all further installation and configuration to be done by .deb packages:"
  echo
  echo "  - Flashed with Edison firmware image (Yocto Linux)"
  echo "  - Root password set"
  echo "  - Debian GNU/Linux 7 (within a /home/root/debian chroot inside Yocto)"
  echo "  - Yocto configured to execute Debian startup scripts on startup"
  echo
  echo "<setup-ssid> should be a network with Internet access that the Edison"
  echo "will use during this setup process to download and install software."
  echo "It can be a wifi network with no password or with a PSK password."
  echo
  echo "If <repo-url> is specified, it will be added as a source for apt-get."
  exit 1
fi

TOOLS=../../tools
start=$(date)

# Get sudo access before possibly initiating a long download.
sudo echo $start

# Flash the Edison with a firmware file from the Intel site.
$TOOLS/fetch_or_skip http://downloadmirror.intel.com/24389/eng/edison-image-rel1-maint-rel1-ww42-14.zip /tmp/edison-firmware.zip 9a7509341cbf936c662af3e46f1b0f34
sudo ./replace-firmware /tmp/edison-firmware.zip
flashed=$(date)
echo $flashed

# Set up the root password.
./configure-root-access "$password"

# Leave the repo URL where usr/local/bin/install-buendia-base will find it.
[ -n "$repo_url" ] && cat <<EOF | do_in_yocto
echo deb [arch=all] '$repo_url' stable main > /etc/buendia-base.sources.list
EOF

# Copy all the setup files and scripts onto the Edison.
echo 'tar cf /var/backups/systemd.tar /etc/systemd /lib/systemd/system' | do_in_yocto
tar cf - etc lib usr | $ssh $target 'tar xf - -C /; systemctl daemon-reload'

# The above step updates sshd.socket, moving sshd to port 9022 instead of 22.
ssh_port=9022

# Ensure that the Edison can connect to the setup network.  This has the side
# effect of updating the wpa_supplicant configuration; enabling wpa_supplicant
# causes the Edison to automatically try to reconnect to this network on boot.
cat <<EOF | do_in_yocto
/usr/local/bin/wifi '$setup_ssid_psk'
systemctl enable wpa_supplicant.service
EOF

# Reboot to continue installation.
echo 'sync; reboot || true' | do_in_yocto
reboot=$(date)

echo
echo "$start - started"
echo "$flashed - finished writing firmware"
echo "$reboot - rebooting to continue installation"
echo
echo "It is safe to disconnect the Edison from this machine now."
echo
echo "When the Edison next boots up, or if it remains connected to power now,"
echo "it will proceed to install Debian and set up the Buendia base system."
