#!/bin/bash

cd $(dirname $0)
target=$1
omod=$2

if [ "$1" == "-h" -o -z "$omod" ]; then
  echo "Usage: $0 <hostname> <filename.omod>"
  echo
  echo "Installs a Buendia OMOD file in an OpenMRS server, replacing any"
  echo "existing Buendia module and restarting the server to pik up the change".
  exit 1
fi

export TARGET=$target
source remote-execution.sh

omodname=$(basename $omod)
tempname=$omodname.$$
scp $omod $target:/tmp/$tempname

cat <<EOF >> /tmp/install_omod.$$

function restart() {
  service=\$1
  if [ -x "\$(which systemctl)" ]; then
    systemctl restart \$service
  else
    service \$service restart
  fi
}

function check_url() {
  retry_count=0
  while [[ \$retry_count -lt 40 ]]; do
    echo "Trying \$@..."
    if curl -s --max-time 10 -i -L \$@ 1>/dev/null; then
      return 0
    fi
    let retry_count=retry_count+1
    sleep 5
  done
  false
}

set -e
cd /usr/share/tomcat7/.OpenMRS

echo
echo "Previous set of modules:"
ls -l modules

mkdir -p old_modules

# old names start with "projectbuendia"; new names start with "buendia-server".
mv -f modules/projectbuendia*omod modules/buendia-server*omod old_modules 2>/dev/null || true

cp -f /tmp/$tempname $tempname  # get the file onto the same filesystem
mv -f $tempname modules/$omodname  # atomically install the file into modules/
rm -f /tmp/$tempname

echo
echo "New set of modules:"
ls -l modules

echo
echo "Restarting tomcat7..."
restart tomcat7

echo
echo "Waiting for new module to come up..."
echo

# Tomcat
check_url http://localhost:8080/

# OpenMRS
check_url http://localhost:8080/openmrs

# Buendia
check_url http://localhost:8080/openmrs/ws/rest/v1/projectbuendia/user -u android:Android123

echo
echo
echo "\o/  Success!  Module $omod installed and running."
echo

EOF

scp /tmp/install_omod.$$ $target:/tmp
echo "sudo bash /tmp/install_omod.$$" | do_remote
