#!/bin/bash
# Copyright 2015 The Project Buendia Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

TOOLS=$(cd $(dirname $0) && pwd)
if [ -n "$1" ]; then
    cd "$1"
fi

names=$(ls | grep '\.deb' | sed -e 's/_.*//' | sort | uniq)

for name in $names; do
    last=$(ls -t $name*.deb | head -1)
    second_last=$(ls -t $name*.deb | head -2 | tail -1)

    if [[ $last =~ _([0-9]+\.[0-9]+) ]]; then
        last_minor=$BASH_REMATCH
    fi
    if [[ $second_last =~ _([0-9]+\.[0-9]+) ]]; then
        second_last_minor=$BASH_REMATCH
    fi

    if [ -n "$last_minor" -a "$last_minor" != "$second_last_minor" ]; then
        echo "different minor versions between $last and $second_last; skipping"
    elif [ "$last" != "$second_last" ] && $TOOLS/diffdeb $last $second_last; then
        echo "removing $last (no substantive changes from $second_last)"
        rm $last
    fi
done
