#!/bin/bash

TOOLS=$(cd $(dirname $0) && pwd)
names=$(ls | grep '\.deb' | sed -e 's/_.*//' | sort | uniq)

for name in $names; do
    last=$(ls -t $name*.deb | head -1)
    second_last=$(ls -t $name*.deb | head -2 | tail -1)
    if [ "$last" != "$second_last" ] && $TOOLS/diffdeb $last $second_last; then
        echo "removing $last (no substantive changes from $second_last)"
        rm $last
    fi
done
