#!/bin/bash
# Copyright 2015 The Project Buendia Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

verbose=$1
if [ "$verbose" == "-v" ]; then
    shift
else
    verbose=""
fi
a=$1
b=$2
if [ "$b" = "" ]; then
    echo "Usage: $0 [-v] <file1.deb> <file2.deb>"
    echo "Exits with status 0 if the contents of two .deb files are"
    echo "functionally identical except for the declared version number"
    echo "(\"Version:\") in the control file.  Otherwise exits with status 1."
    echo
    echo "Appending the -v flag causes the script to display the differences"
    echo "between packages."
    exit 1
fi

if [ -n "$verbose" ]; then
    echo "comparing $a <> $b"
fi

TAR=$(which gtar || which tar)  # we need GNU tar for a proper comparison
atmp=/tmp/diffdeb.$$.1
btmp=/tmp/diffdeb.$$.2

if [ -z "$verbose" ]; then
    trap 'rm -rf $atmp $btmp' EXIT
fi

# Unpacks a .deb file into a directory ready for comparison.  The file named
# "deb" is destructively unpacked into the current directory, and the contents
# of data.tar.gz and control.tar.gz are destructively unpacked as well.
# The control file is then edited to remove the Version line.
function unpack_and_remove_version() {
    # Unpack deb -> control.tar.gz, data.tar.gz, debian-binary
    ar x deb
    rm deb

    # Unzip data.tar so that we can diff independently of stored timestamps.
    $TAR xfz data.tar.gz

    # Unpack control.tar.gz for same, and delete the "Version:" line
    $TAR xfz control.tar.gz
    grep -v '^Version: ' control > control.unversioned
    touch -t 197001010000 control.unversioned
    rm control control.tar.gz data.tar.gz
}

mkdir -p $atmp $btmp
cp $a $atmp/deb
cp $b $btmp/deb

cd $atmp
unpack_and_remove_version
cd $btmp
unpack_and_remove_version

if [ -n "$verbose" ]; then
    diff -r $atmp $btmp
else
    diff -q -r $atmp $btmp >/dev/null
fi
