#!/bin/bash

url=$1
dest=$2
expected_hash=$3

if [ "$expected_hash" == "" ]; then
    echo "Usage: $0 <url> <destination-path> <expected-md5-hash>"
    echo "Fetches a file from a URL to a local path.  If a file already exists"
    echo "at the local path with the given MD5 hash, skips the fetch.  Useful"
    echo "for fetching large files and avoiding unnecessary refetches."
fi

md5=$(which md5 || which md5sum)

hash=$($md5 $dest | grep -o '[0-9a-f]\{32\}') || true
if [ "$hash" == "$expected_hash" ]; then
    echo $dest is up to date.
else
    echo Fetching $dest...
    mkdir -p $(dirname "$dest")
    curl -o "$dest" -L "$url"
fi
