#!/bin/bash

# Given a directory full of *.sql table schemas, produces the SQL commands to
# replace all the foreign key references to users.user_id with @buendia_admin.

for i in *.sql; do
    grep -i 'references.*`users`.*`user_id`' $i | sed -e 's/.*FOREIGN KEY [^(]*(`\([^`]*\)`.*/UPDATE '${i%.sql}' SET \1 = @buendia_admin_id WHERE \1 IS NOT NULL AND \1 != @admin_id;/'
    echo
done
