#!/bin/bash
# Copyright 2015 The Project Buendia Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

# Given a directory full of *.sql table schemas, produces the SQL commands to
# replace all the foreign key references to users.user_id with @buendia_admin.

for i in *.sql; do
    grep -i 'references.*`users`.*`user_id`' $i | sed -e 's/.*FOREIGN KEY [^(]*(`\([^`]*\)`.*/UPDATE '${i%.sql}' SET \1 = @buendia_admin_id WHERE \1 IS NOT NULL AND \1 != @admin_id;/'
    echo
done
