#!/bin/bash

account=projectbuendia
repo="$1"
buildnum="$2"

if [ "$1" = "-h" -o "$repo" = "" -o "$buildnum" = "" ]; then
    echo 'Usage: get_artifacts <repo-name> <build-number>'
    echo
    echo 'Downloads all the artifacts from the specified CircleCI build for'
    echo 'the given repo (in the "projectbuendia" GitHub organization).'
    echo 'The environment variable CIRCLE_TOKEN should be set to a valid'
    echo 'CircleCI API token.'
    exit 1
fi

if [ "$CIRCLE_TOKEN" = "" ]; then
    echo 'CIRCLE_TOKEN should be set to a valid CircleCI API token.'
    exit 1
fi

echo "Getting list of artifacts for projectbuendia/$repo, build $buildnum..."

curl -s "https://circleci.com/api/v1.1/project/github/projectbuendia/$repo/$buildnum/artifacts?circle-token=$CIRCLE_TOKEN" | grep -o 'https://[^"]*' > /tmp/artifacts.txt

echo
echo "Downloading artifacts:"

for url in $(cat /tmp/artifacts.txt); do
  path=$(echo $url | sed -e 's-.*/tmp/artifacts/*--')
  dir=$(dirname $path)
  echo $path
  mkdir -p "$dir"
  curl -s -o "$path" "$url"?circle-token="$CIRCLE_TOKEN"
done
