#!/bin/bash
# Copyright 2015 The Project Buendia Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

root_url=$1
username=$2
password=$3
name=$(basename $0)

if [ "$password" = "" ]; then
    echo "Usage: $0 <openmrs-root-url> <username> <password>"
    echo
    echo "Gets all patients from the Buendia API at the OpenMRS server with"
    echo "the given root URL, using the given OpenMRS user and password."
    echo "Outputs the JSON dictionary for each patient on a new line."
    exit 1
fi

root_url=${root_url%/}

(curl -s -X GET $root_url/ws/rest/buendia/patients -u "$username:$password" | sed -e 's/},{/}\n{/g' -e 's/^{"results":\[//' -e 's/}]}$/}/'; echo) | grep uuid
