#!/bin/bash
# Copyright 2015 The Project Buendia Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

set -e
eval $(buendia-settings 2>/dev/null)

MYSQL_USER=${MYSQL_USER-$OPENMRS_MYSQL_USER}
MYSQL_PASSWORD=${MYSQL_PASSWORD-$OPENMRS_MYSQL_PASSWORD}
DATABASE_NAME=${DATABASE_NAME-openmrs}

if [ -z "$MYSQL_USER" ]; then
    echo '$MYSQL_USER is not set; please set $MYSQL_USER and $MYSQL_PASSWORD.'
    exit 1
fi

mysql -u $MYSQL_USER -p$MYSQL_PASSWORD $DATABASE_NAME "$@"
