#!/bin/bash

set -e
db=$1
dumpfile=$2
pwd=$(pwd)

mysql="mysql"
if [ -n "$MYSQL_USER" ]; then
    mysql="mysql -u $MYSQL_USER -p$MYSQL_PASSWORD"
fi

if [ -z "$dumpfile" ]; then
    echo "Usage: $0 <database-name> <dump-file.zip>"
    echo 'Wipes a MySQL database and loads a dump file into it.'
    echo
    echo 'Requires a MySQL user that has been granted database access with'
    echo '    GRANT USAGE ON <database-name>.* to <user>@<host>'
    echo 'Specify the user and password with $MYSQL_USER and $MYSQL_PASSWORD.'
    echo
    exit 1
fi

tmpdir=/tmp/openmrs_load.$$
tmpzip=/tmp/openmrs_dump.$$.zip
function cleanup() {
    rm -rf $tmpdir $tmpzip
}
trap cleanup EXIT

# Create an empty database.
if $mysql -s -e "create database $db" 2>/dev/null; then
  echo 'Created a new empty database.'
else
  echo "Wiping existing database $db..."
  $mysql -s -e 'show tables;' $db | sed -e 's/^/; set session foreign_key_checks=0; drop table /' | $mysql $db
fi

# Unpack the zip file in the temporary directory.
mkdir -p $tmpdir
cp $dumpfile $tmpzip
cd $tmpdir
echo 'Unpacking $dumpfile...'
unzip -q -j $tmpzip

# Load the data.
$mysql --local-infile --unbuffered -s -e 'source 000_load.sql;' $db
