#!/bin/bash
# Copyright 2015 The Project Buendia Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

set -e
if [ "$1" = "-f" ]; then
    force=yes
    shift
fi
db=$1
dumpfile=$2
pwd=$(pwd)

if [ -z "$dumpfile" ]; then
    echo "Usage: $0 [-f] <database-name> <dump-file.zip>"
    echo
    echo 'Loads a dump file (made with openmrs_dump) into a MySQL database.'
    echo
    echo 'Requires $MYSQL_USER and $MYSQL_PASSWORD to be set to valid'
    echo 'credentials for a MySQL user that has been granted access with:'
    echo '    GRANT USAGE ON <mysql_database>.* to <mysql_user>@<host>'
    exit 1
fi

eval $(buendia-settings 2>/dev/null)

MYSQL_USER=${MYSQL_USER-$OPENMRS_MYSQL_USER}
MYSQL_PASSWORD=${MYSQL_PASSWORD-$OPENMRS_MYSQL_PASSWORD}

if [ -z "$MYSQL_USER" ]; then
    echo '$MYSQL_USER is not set; please set $MYSQL_USER and $MYSQL_PASSWORD.'
    exit 1
fi

if [ ! -f "$dumpfile" ]; then
    echo "$dumpfile: no such file."
    exit 1
fi

tmpdir=/tmp/openmrs_load.$$
tmpzip=/tmp/openmrs_dump.$$.zip
trap 'rm -rf $tmpdir $tmpzip' EXIT

export MYSQL_PWD="$MYSQL_PASSWORD"
MYSQL="mysql -u $MYSQL_USER"

# Create an empty database.
if $MYSQL -e '' $db 2>/dev/null; then
    if [ "$force" = yes ]; then
        echo "Wiping existing database $db..."
        $MYSQL -s -e "drop database $db"
    else
        echo "A database named "\"$db\"" already exists!  To wipe and replace it, use -f."
        exit 1
    fi
fi
if $MYSQL -s -e "create database $db charset utf8" 2>/dev/null; then
    echo "Created a new empty database named "\"$db\""."
else
    echo "Failed to create a new "\"$db\"" database."
    exit 1
fi

# Unpack the zip file in the temporary directory.
mkdir -p $tmpdir
cp $dumpfile $tmpzip
cd $tmpdir
echo "Unpacking $dumpfile..."
unzip -q -j $tmpzip

# Load the data.
$MYSQL --local-infile --unbuffered -s -e 'source 000_load.sql;' $db
