#!/bin/bash -e
# Copyright 2015 The Project Buendia Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

# Sets up a local OpenMRS server with a MySQL database, for development.

SERVER_ID=buendia
OPENMRS_DIR=$HOME/openmrs
# This version number is duplicated in [git root]/openmrs/pom.xml
PLATFORM_VERSION=2.2.0  # TODO: db-snapshot data is only for 1.10.x

if [ "$1" = "-f" ]; then
    force_flag="-f"
fi
cd $(dirname $0)/..  # go to the root of the Buendia git repo

if [ "$1" = "-h" ]; then
    echo "Usage: $0 [-f]"
    echo
    echo 'Installs the OpenMRS platform, configures it to use MySQL, sets up'
    echo 'the MySQL user "openmrs" with the password "openmrs", and'
    echo 'initializes the MySQL database from the contents of the db-snapshot'
    echo 'directory.  By default, this will refuse to overwrite the MySQL'
    echo 'database named "openmrs" if it already exists; specify -f to wipe'
    echo 'and replace the existing database.'
    echo
    exit 1
fi

# Make a fresh, empty "openmrs" database.
if mysql -uopenmrs -popenmrs -e '' openmrs 2>/dev/null; then
    if ! [ "$force_flag" = "-f" ]; then
        echo "A database named "\"openmrs\"" already exists!  To wipe and replace it, use -f."
        exit 1
    fi
    echo "Deleting the existing "\"openmrs\"" database."
fi
echo "If prompted, please enter your sudo password:"
sudo mysql -uroot -p 2>/dev/null <<< "
    drop database if exists openmrs;
    create database if not exists openmrs;
    grant all on openmrs.* to openmrs@localhost identified by 'openmrs';
    grant file on *.* to openmrs@localhost;
    flush privileges;
"
echo "Created an empty "\"openmrs\"" database."

tools/openmrs_ensure_sdk

# Ensure that an OpenMRS server named "buendia" exists.
if [ ! -f $OPENMRS_DIR/$SERVER_ID/openmrs-$PLATFORM_VERSION.war ]; then
    echo
    echo 'Get ready to answer the following prompts:'
    echo '  - For the port number, press Enter to accept the default'
    echo '  - For debugging, press Enter to accept "no debugging" by default'
    echo '  - For MySQL, choose MySQL 5.6 (option 1)'
    echo '  - For the JDK, choose an option with version 1.8 or newer'
    echo
    echo -n 'Please make a note of the above.  Ready? '
    read
    # Set up a new OpenMRS server with the legacy UI
    mvn openmrs-sdk:setup -DserverId=$SERVER_ID -Dplatform=$PLATFORM_VERSION -DdbUri=jdbc:mysql://localhost:3306/openmrs -DdbUser=openmrs -DdbPassword=openmrs
    mvn openmrs-sdk:deploy -DserverId=$SERVER_ID -DgroupId=org.openmrs.module -DartifactId=legacyui -Dversion=1.5.0
fi

# Running from Linux or Mac? Set the appropriate path.
BUENDIA_DIR='/usr/share/buendia'
BIN_DIR='/usr/bin'
OS=`uname`
if [[ "$OS" == 'Darwin' ]]; then
    BUENDIA_DIR='/usr/local/opt/buendia'
    BIN_DIR='/usr/local/bin'
fi
PROFILE_DIR="$BUENDIA_DIR/profiles"

# TODO: remove the need for sudo
# Create directories and copy scripts
echo "If prompted, please enter your sudo password:"
sudo mkdir -p $PROFILE_DIR
sudo cp -p tools/profile_validate "$BIN_DIR/buendia-profile-validate"
sudo cp -p packages/buendia-utils/data/usr/share/buendia/utils.sh "$BUENDIA_DIR/utils.sh"

# In the profile_apply script there is a hardcoded reference to utils.sh. sed will replace this by a mac friendly path.
# We then have to chmod this file to ensure that buendia-profile-apply can be executed.
# TODO: review this after system wide path related changes.
if [[ "$OS" == 'Darwin' ]]; then
    sed 's/\/usr\/share/\/usr\/local\/opt/g' tools/profile_apply | sudo tee "$BIN_DIR/buendia-profile-apply" > /dev/null
    sudo chmod a+x "$BIN_DIR/buendia-profile-apply"
else
    sudo cp -p tools/profile_apply "$BIN_DIR/buendia-profile-apply"
fi

# Set permissions
current_user=`whoami`
sudo chown -R "$current_user" "$BUENDIA_DIR"
sudo chmod -R 755 $BUENDIA_DIR

# Configure OpenMRS to use the openmrs MySQL account.
cat <<EOF >$OPENMRS_DIR/$SERVER_ID/openmrs-runtime.properties
connection.username=openmrs
connection.password=openmrs
auto_update_database=false
profile_manager.profile_dir=$PROFILE_DIR
EOF
echo 'Configured OpenMRS to use the MySQL user openmrs@localhost.'

# Get the latest database snapshot.
git submodule update --init db-snapshot
zip -qj /tmp/init.$$.zip db-snapshot/*
trap 'rm -f /tmp/init.$$.zip' EXIT

# Load the snapshot into the MySQL database.
export MYSQL_USER=openmrs
export MYSQL_PASSWORD=openmrs
echo
tools/openmrs_load $force_flag openmrs /tmp/init.$$.zip

# Set up the OpenMRS account for Buendia.
tools/openmrs_account_setup buendia buendia

echo
echo 'Database initialization completed.'
