#!/bin/bash -e
# Copyright 2019 The Project Buendia Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

if [ "$1" = "-h" ]; then
    echo "Usage: $0"
    echo
    echo "Ensures that the OpenMRS SDK is installed."
    exit 1
fi

if ! [ -e $HOME/openmrs/.sdk-installed ]; then
    # Creating this file causes the setup-sdk task to skip asking the user
    # for consent to collect anonymous usage statistics.
    mkdir -p $HOME/openmrs
    touch $HOME/openmrs/sdk-stats.properties

    # Install the OpenMRS SDK plugin.
    mvn org.openmrs.maven.plugins:openmrs-sdk-maven-plugin:setup-sdk

    touch $HOME/openmrs/.sdk-installed
    echo "OpenMRS SDK is ready."
fi
