#!/bin/bash
# Copyright 2019 The Project Buendia Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

# Ensure that the correct version of the OpenMRS platform WAR has been
# downloaded and configured.

SERVER_ID=server
SERVER_DIR=$HOME/openmrs/$SERVER_ID
PLATFORM_VERSION=1.10.2
WAR_URL=http://sourceforge.net/projects/openmrs/files/releases/OpenMRS_Platform_${PLATFORM_VERSION}/openmrs.war/download
WAR_MD5=7e8d4054d86d796018c9fca31f4d33b2

# go to the root of the Buendia repository
cd $(dirname $0)/..

# Install the OpenMRS SDK configuration properties if needed.
if [ ! -d $SERVER_DIR ]; then
    echo "Configuring OpenMRS SDK..."
    mkdir -p $SERVER_DIR
    # Install the properties files so that the setup-sdk task doesn't ask
    cp -a openmrs/properties/*.properties $SERVER_DIR/..
    # Then run setup-sdk so that the Maven cache gets populated
    mvn org.openmrs.maven.plugins:openmrs-sdk-maven-plugin:setup-sdk -DserverId=$SERVER_ID
fi

# Install the OpenMRS WAR if needed.
OPENMRS_WAR_FILE=$SERVER_DIR/openmrs-$PLATFORM_VERSION.war
if [ ! -f $OPENMRS_WAR_FILE ]; then
    echo "Fetching OpenMRS platform WAR..."
    tools/fetch $WAR_URL $WAR_MD5 $OPENMRS_WAR_FILE
    echo "Installing default OpenMRS properties..."
    cp -a openmrs/properties/$SERVER_ID/* $SERVER_DIR
fi

echo "OpenMRS SDK ready."
