#!/bin/bash
# Copyright 2015 The Project Buendia Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

# Starts a local OpenMRS server for development.

set -e
SERVER_ID=server

# Serve on port 9000 to match production.
PORT_OPTS="-Djetty.port=9000 -Dserver.port=9000 -Dport=9000"

# Increase memory limits.
MEMORY_OPTS="-Xmx2G -XX:MaxPermSize=128m"

# Enable remote debugging.
# DEBUG_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"

# Go to the OpenMRS installation directory.
if [ ! -d $HOME/openmrs/$SERVER_ID ]; then
    echo "OpenMRS server not installed; run openmrs_setup first."
    exit 1
fi
cd $HOME/openmrs/$SERVER_ID

# Start the server.
export MAVEN_OPTS="$PORT_OPTS $MEMORY_OPTS $DEBUG_OPTS"
mvn openmrs-sdk:run
