#!/bin/bash
# Copyright 2015 The Project Buendia Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

# Builds the Buendia module and installs it in an OpenMRS development server.

set -e
SERVER_ID=server
SERVER_DIR=$HOME/openmrs/$SERVER_ID
MODULE_DIR=$SERVER_DIR/modules
INSTALL="mvn openmrs-sdk:deploy -DserverId=$SERVER_ID"
cd $(dirname $0)
cd ..  # go to the root of the Buendia repository

# Install the OpenMRS SDK.
mvn org.openmrs.maven.plugins:openmrs-sdk-maven-plugin:setup-sdk

# Clean out any old modules, leaving an empty server module directory.
rm -rf $MODULE_DIR
mkdir -p $MODULE_DIR

# openmrs-sdk:install requires an installation.properties file containing
# connection.url and database_name properties.  If it's not there, create
# a temporary properties file so that the rest of this script will work.
if [ ! -f $SERVER_DIR/installation.properties ]; then
    cat <<EOF >$SERVER_DIR/installation.properties
connection.url=jdbc\:mysql\://localhost\:3306/openmrs
database_name=openmrs
EOF
    trap 'rm -f $SERVER_DIR/installation.properties' EXIT
fi

# Install the module dependencies in the OpenMRS development server.
# These version numbers are duplicated in [git root]/openmrs/pom.xml
$INSTALL -DgroupId=org.openmrs.module -DartifactId=xforms -Dversion=4.3.5
$INSTALL -DgroupId=org.openmrs.module -DartifactId=webservices.rest -Dversion=2.6

# Build the Buendia module, passing along any flags (e.g. -DskipTests)
# given to this script.
cd openmrs
mvn clean install "$@"

# Install the module in the OpenMRS development server.
$INSTALL -DgroupId=org.projectbuendia -DartifactId=projectbuendia.openmrs -Dversion=1.0-SNAPSHOT
