#!/bin/bash
# Copyright 2015 The Project Buendia Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

# Sets up the OpenMRS account used for Buendia API requests.

set -e
if [ "$1" == "-h" ]; then
    echo "Usage: $0"
    echo
    echo "Sets up a small default location hierarchy for testing."
    echo
    echo 'Requires a MySQL user that has been granted database access with'
    echo '    GRANT USAGE ON <database-name>.* to <user>@<host>'
    echo 'Specify the user and password with $MYSQL_USER and $MYSQL_PASSWORD.'
    echo
    exit 1
fi

eval $(buendia-settings 2>/dev/null)

MYSQL_USER=${MYSQL_USER-$OPENMRS_MYSQL_USER}
MYSQL_PASSWORD=${MYSQL_PASSWORD-$OPENMRS_MYSQL_PASSWORD}

if [ -z "$MYSQL_USER" ]; then
    echo '$MYSQL_USER is not set; please set $MYSQL_USER and $MYSQL_PASSWORD.'
    exit 1
fi

MYSQL="mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -s -N openmrs"
USER_ID=$($MYSQL <<< "
    select user_id from users where username = 'buendia_admin';
" 2>/dev/null)

function randhex() {
    xxd -l $(($1 / 2)) -p /dev/urandom | tr -d '\n'
}

function uuidgen() {
    randhex 32 | sed -e 's/\(........\)\(....\)\(....\)\(....\)\(............\)/\1-\2-\3-\4-\5/'
}

function add_location() {
    name="$1"
    parent_id="$2"
    uuid=$(uuidgen)
    $MYSQL <<< "
        insert into location
            (name, parent_location, creator, date_created, uuid)
        values
            ('$name', $parent_id, '$USER_ID', now(), '$uuid');
    " >/dev/null;
    echo 'Added location "'$name'".'
    $MYSQL <<< "
        select location_id from location where uuid = '$uuid';
    "
}

$MYSQL <<< "
    update location set retired = 1;
";

etc=$(add_location "[1] Bunia ETC" null)
triage=$(add_location "[2] Triage" $etc)
suspected=$(add_location "[3] Suspected" $etc)
confirmed=$(add_location "[4] Confirmed" $etc)
discharged=$(add_location "[5] Discharged" null)
