#!/bin/bash
# Copyright 2015 The Project Buendia Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

# Starts a local OpenMRS server for development.

## Usage:
##   tools/openmrs_run [-p PORTNUM] [--debug]
##
## Note that it's possible to change the OpenMRS server ID by setting OPENMRS_SERVER.

set -e

PORT="9000"
DEBUG=0

while [[ $# > 1 ]]
  do
  key="$1"

  case $key in
    -p)
      PORT="$2"
      shift # past argument
      ;;
    --debug)
      DEBUG=1
      ;;
  esac
  shift # past argument or value
done


if [ -z "$OPENMRS_SERVER" ]; then
  SERVER_ID="server"
else
  SERVER_ID="$OPENMRS_SERVER"
fi

# Serve on port 9000 to match production.
PORT_OPTS="-Djetty.port=$PORT"

# Increase memory limits.
MEMORY_OPTS="-Xmx2G -XX:MaxPermSize=128m"

# Enable remote debugging.
if [ "$DEBUG" -eq 1 ]; then
  DEBUG_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
else
  DEBUG_OPTS=""
fi

# Go to the OpenMRS installation directory.
if [ ! -d $HOME/openmrs/$SERVER_ID ]; then
    echo "OpenMRS server not installed; run openmrs_setup first."
    exit 1
fi
cd $HOME/openmrs/$SERVER_ID

# Start the server.
export MAVEN_OPTS="$PORT_OPTS $MEMORY_OPTS $DEBUG_OPTS"
mvn openmrs-sdk:run
