#!/bin/bash -e

echo
echo 'This will reinitialize the entire OpenMRS dev environment and database.'
echo
echo 'ALL CONFIGURATION SETTINGS AND DATA WILL BE LOST.'
echo
echo -n 'Are you sure (type "yes")? '
read answer

if [ $answer = yes ]; then
    rm -rf $HOME/openmrs/buendia
    tools/openmrs_clean &&
        tools/openmrs_setup -f &&
        tools/openmrs_build -DskipTests &&
        tools/openmrs_run
fi
