#!/bin/bash

tools=$(cd $(dirname "$0") && pwd)

if [ -z "$1" ]; then
    echo "Usage: $0 <grep-options> <keyword>"
    echo
    echo "Shows all the lines in the Buendia package control files that"
    echo "contain the (case-insensitive) keyword.  Examples:"
    echo
    echo "    pkginfo depend - shows you all the dependencies"
    echo "    pkginfo description - shows you all the descriptions"
    exit 1
fi

cd $tools/../packages
grep -i "$@" */control/control.template | sed -e 's#/control/control.template:#: #'
