#!/bin/bash
# Copyright 2019 The Project Buendia Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

# Tells the server to clear its per-session entity cache.

set -e

eval $(buendia-settings 2>/dev/null)

curl -u "$SERVER_OPENMRS_USER:$SERVER_OPENMRS_PASSWORD" -sS \
    'http://localhost:9000/openmrs/ws/rest/buendia/providers?clear-cache=1' >/dev/null
